"""
Base agent definitions for the Democracy Desk multi-agent system.
This module defines the abstract interface that all specialized agents must implement.
"""
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel

class AgentResponse(BaseModel):
    """
    Standard response format for all agents.
    
    Attributes:
        agent_name: The name of the agent providing the response.
        content: The primary text content or response.
        metadata: Any structured data generated by the agent.
    """
    agent_name: str
    content: str
    metadata: Dict[str, Any] = {}

class BaseAgent(ABC):
    """
    Abstract base class for all election education agents.
    
    All agents should inherit from this class and implement the `process` method.
    """
    def __init__(self, name: str):
        """
        Initialize the agent with a unique name.
        
        Args:
            name: The human-readable name of the agent.
        """
        self.name = name

    @abstractmethod
    async def process(self, task: str, context: Optional[Dict[str, Any]] = None) -> AgentResponse:
        """
        Process a user query or internal task.
        
        Args:
            task: The main input string/task.
            context: Optional dictionary containing context from previous agents.
            
        Returns:
            An AgentResponse containing the result of processing.
        """
        pass
